[package]
name = "resim"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.7"
plotters = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.1"
chrono = "0.4.38"
indexmap = "2.6.0"
